taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    DriverListView,
    DriverDetailView,
    DriverCreateView,
    DriverLicenseUpdateView,
    DriverDeleteView,
    ManufacturerListView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    toggle_assign_to_car,
)

urlpatterns = [
    path("", index, name="index"),

    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path(
        "manufacturers/create/",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create",
    ),
    path(
        "manufacturers/<int:pk>/update/",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update",
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete",
    ),

    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", CarCreateView.as_view(), name="car-create"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("cars/<int:pk>/toggle-assign/", toggle_assign_to_car, name="toggle-car-assign"),

    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/create/", DriverCreateView.as_view(), name="driver-create"),
    path(
        "drivers/<int:pk>/update/",
        DriverLicenseUpdateView.as_view(),
        name="driver-update",
    ),
    path("drivers/<int:pk>/delete/", DriverDeleteView.as_view(), name="driver-delete"),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model

taxi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from taxi.models import Car, Driver


class CarForm(forms.ModelForm):
    drivers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Car
        fields = "__all__"


class DriverCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Driver
        fields = UserCreationForm.Meta.fields + (
            "license_number", "first_name", "last_name",
        )

    def clean_license_number(self):  # this logic is optional, but possible
        return validate_license_number(self.cleaned_data["license_number"])


class DriverLicenseUpdateForm(forms.ModelForm):

    class Meta:
        model = Driver
        fields = ["license_number"]

    def clean_license_number(self):
        return validate_license_number(self.cleaned_data["license_number"])


def validate_license_number(license_number):  # regex validation is also possible here
    if len(license_number) != 8:
        raise ValidationError("License number should consist of 8 characters")
    elif not license_number[:3].isupper() or not license_number[:3].isalpha():
        raise ValidationError("First 3 characters should be uppercase letters")
    elif not license_number[3:].isdigit():
        raise ValidationError("Last 5 characters should be digits")

    return license_number


class CarSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by model..."})
    )


class ManufacturerSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class DriverSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Driver, Car, Manufacturer
from .forms import DriverCreationForm, DriverLicenseUpdateForm, CarForm
from .forms import ManufacturerSearchForm, DriverSearchForm, CarSearchForm


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ManufacturerListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = ManufacturerSearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        queryset = Manufacturer.objects.all()
        form = ManufacturerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    success_url = reverse_lazy("taxi:manufacturer-list")


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        model = self.request.GET.get("model", "")
        context["search_form"] = CarSearchForm(initial={
            "model": model
        })
        return context

    def get_queryset(self):
        queryset = Car.objects.select_related("manufacturer")
        form = CarSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                model__icontains=form.cleaned_data["model"]
            )
        return queryset


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    success_url = reverse_lazy("taxi:car-list")


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DriverListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = DriverSearchForm(initial={
            "username": username
        })
        return context

    def get_queryset(self):
        queryset = Driver.objects.all()
        form = DriverSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm


class DriverLicenseUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverLicenseUpdateForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    success_url = reverse_lazy("taxi:driver-list")


@login_required
def toggle_assign_to_car(request, pk):
    driver = Driver.objects.get(id=request.user.id)
    if Car.objects.get(id=pk) in driver.cars.all():  # probably could check if car exists
        driver.cars.remove(pk)
    else:
        driver.cars.add(pk)
    return HttpResponseRedirect(reverse_lazy("taxi:car-detail", args=[pk]))

templates/taxi/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete car?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ car.model }}
    <a href="{% url 'taxi:car-delete' pk=car.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'taxi:car-update' pk=car.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p><strong>Manufacturer: </strong>{{ car.manufacturer.name }} ({{ car.manufacturer.country }})</p>

  <div class="ml-3">
  <h3>
    Drivers

    {% if car in user.cars.all %}
      <a href="{% url 'taxi:toggle-car-assign' pk=car.id %}" class="btn btn-danger link-to-page">
        Delete me from this car
      </a>
    {% else %}
      <a href="{% url 'taxi:toggle-car-assign' pk=car.id %}" class="btn btn-success link-to-page">
        Assign me to this car
      </a>
    {% endif %}
  </h3>

    {% for driver in car.drivers.all %}
      <hr>
        <p><strong>Username: </strong>
          <a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a>
        </p>
        <p><strong>Full name: </strong>{{ driver.first_name }} {{ driver.last_name }}</p>
        <p><strong>License number: </strong>{{ driver.license_number }}</p>

      {% empty %}
      <p>No drivers!</p>

    {% endfor %}
  </div>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} car</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>Taxi Service | Cars</title>{% endblock %}

{% block content %}
  <h1>
    Car list
    <a href="{% url 'taxi:car-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>

  {% if car_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Model</th>
        <th>Manufacturer name</th>
        <th>Manufacturer country</th>
      </tr>
    {% for car in car_list %}
      <tr>
        <td><a href="{% url "taxi:car-detail" pk=car.id %}">{{ car.id }}</a></td>
        <td>{{ car.model }}</td>
        <td>{{ car.manufacturer.name }}</td>
        <td>{{ car.manufacturer.country }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no cars in taxi.</p>
    {% endif %}
{% endblock %}

templates/taxi/driver_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete driver?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
    <a href="{% url 'taxi:driver-delete' pk=driver.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'taxi:driver-update' pk=driver.id %}" class="btn btn-secondary link-to-page">
      Update license number
    </a>
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}</p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-3">
    <h3>Cars</h3>

    {% for car in driver.cars.all %}
        <hr>
        <p><strong>Model:</strong> {{ car.model }}</p>
        <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }} ({{ car.manufacturer.country }})</p>
        <p class="text-muted"><strong>Id:</strong>
          <a href="{% url "taxi:car-detail" pk=car.id %}">{{ car.id }}</a>
        </p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} driver</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>Taxi Service | Drivers</title>{% endblock %}

{% block content %}
    <h1>
      Driver List
      <a href="{% url 'taxi:driver-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔎">
    </form>

    {% if driver_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
      </tr>
    {% for driver in driver_list %}
      <tr>
        <td>{{ driver.id }}</td>
        <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a></td>
        <td>{{ driver.first_name }}</td>
        <td>{{ driver.last_name }}</td>
        <td>{{ driver.license_number }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Taxi Service | Home</title>{% endblock %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>

    <img class="home" src="{% static 'images/taxi_1.jpg' %}" alt="Taxi image">

    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete manufacturer?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} manufacturer</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>Taxi Service | Manufacturers</title>{% endblock %}

{% block content %}
  <h1>
    Manufacturer List
    <a href="{% url 'taxi:manufacturer-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>

  {% if manufacturer_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>
              {{ manufacturer.id }}
          </td>
          <td>
              {{ manufacturer.name }}
          </td>
          <td>
              {{ manufacturer.country }}
          </td>
          <td>
              <a href="{% url 'taxi:manufacturer-update' pk=manufacturer.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'taxi:manufacturer-delete' pk=manufacturer.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}